### ISSUE TITLE
ROS Kinetic regression (lib install includes architecture)

### ISSUE THREAD

**Issue by wxmerkt** [stack-of-tasks/eigenpy#116]
This issue is to track the issues with the `eigenpy` package distributed via the ROS buildfarm on Ubuntu 16.04 which affects `pinocchio` (regression, does not build) and `moveit` (works because added `eigenpyConfig.cmake`). Currently, only `pinocchio` and other **pkg-config consumers** are broken.

**Note: This problem only happens on 16.04/kinetic due to the old version of `debhelper`.**

- eigenpy uses `GNUInstallDirs`. On the `ros_buildfarm`, the `CMAKE_INSTALL_FULL_LIBDIR` includes the system architecture for the `pkg-config` file, while the library is correctly installed in `lib/`.
- `libdir` and `pkglibdir` both include the system architecture:

```
cat /opt/ros/kinetic/lib/x86_64-linux-gnu/pkgconfig/eigenpy.pc 
prefix=/opt/ros/kinetic
exec_prefix=/opt/ros/kinetic
**libdir=/opt/ros/kinetic/lib/x86_64-linux-gnu**
bindir=/opt/ros/kinetic/bin
**pkglibdir=/opt/ros/kinetic/lib/x86_64-linux-gnu/eigenpy**
includedir=/opt/ros/kinetic/include
datarootdir=/opt/ros/kinetic/share
pkgdatarootdir=/opt/ros/kinetic/share
docdir=/opt/ros/kinetic/share/doc/eigenpy
doxygendocdir=/opt/ros/kinetic/share/doc/eigenpy/doxygen-html
```

Related issues:
- Issue identified here: https://github.com/ros-infrastructure/ros_buildfarm/issues/543#issuecomment-395249636
- https://github.com/ros-infrastructure/ros_buildfarm/issues/686
- https://github.com/ros/catkin/issues/545

@tfoote: Is there any way of resolving this apart from changing the `rules` in the packaging manually (e.g. https://github.com/mrpt-ros-pkg-release/mrpt1-release/commit/17361d75ef9e73c3496dca74813c4b9ee90ec643)? The most relevant answer to the issue here is from https://github.com/ros-infrastructure/ros_buildfarm/issues/543#issuecomment-395249636

**Comment by tfoote** [comment]
There have been some other projects that hit this bug in the past too: https://github.com/ros/console_bridge/issues/15

With a follow up here: https://github.com/ros/console_bridge/pull/19

**Comment by wxmerkt** [comment]
Thank you @tfoote. I think I found the issue. The cmake-modules that this project depends on sets variables for where to find the library in the pkg-config template that do not match the ones where it actually gets installed to. I will push for a merge + release to the buildfarm today, this should fix the Pinocchio regression.

**Comment by jcarpent** [comment]
Thanks @tfoote and @wxmerkt for the fix. Solved by #120.

**Comment by wxmerkt** [comment]
Thank you. Release made:

- Kinetic: https://github.com/ros/rosdistro/pull/23043
- Melodic: https://github.com/ros/rosdistro/pull/23045 (not required but want to keep both distros in sync)

**Comment by wxmerkt** [comment]
While #120 fixed the mismatch between the pkg-config and the actual installed layout, it didn't resolve the original issue. The toolchain appears to configure in such a way that on Xenial that the system architecture is used in the path (`-DCMAKE_INSTALL_PREFIX=/usr`, which is a special case in `GNUInstallDirs`). This one isn't sourced on the PKG_CONFIG_PATH which is why the dependent Pinocchio build continues to fail. I haven't found a neat work-around yet.
