### ISSUE TITLE
Eigenpy compilation fails with the latest master branch of Eigen

### ISSUE THREAD

**Issue by cmastalli** [stack-of-tasks/eigenpy#190]
This is the message that I found:
```bash
[ 45%] Building CXX object CMakeFiles/eigenpy.dir/src/angle-axis.cpp.o
/usr/bin/c++  -Deigenpy_EXPORTS -I/home/cmastalli/devel/eigenpy/build -I/home/cmastalli/devel/eigenpy/build/include -I/home/cmastalli/devel/eigenpy/include -isystem /usr/local/include/eigen3 -isystem /usr/include/python2.7 -isystem /home/cmastalli/.local/lib/python2.7/site-packages/numpy/core/include  -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion  -O3 -DNDEBUG -fPIC   -Wno-conversion -o CMakeFiles/eigenpy.dir/src/angle-axis.cpp.o -c /home/cmastalli/devel/eigenpy/src/angle-axis.cpp
In file included from /home/cmastalli/devel/eigenpy/src/decompositions/decompositions.cpp:12:0:
/home/cmastalli/devel/eigenpy/include/eigenpy/decompositions/LLT.hpp: In instantiation of ‘void eigenpy::LLTSolverVisitor<_MatrixType>::visit(PyClass&) const [with PyClass = boost::python::class_<Eigen::LLT<Eigen::Matrix<double, -1, -1>, 1>, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>; _MatrixType = Eigen::Matrix<double, -1, -1>]’:
/usr/include/boost/python/def_visitor.hpp:31:9:   required from ‘static void boost::python::def_visitor_access::visit(const V&, classT&) [with V = boost::python::def_visitor<eigenpy::LLTSolverVisitor<Eigen::Matrix<double, -1, -1> > >; classT = boost::python::class_<Eigen::LLT<Eigen::Matrix<double, -1, -1>, 1>, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>]’
/usr/include/boost/python/def_visitor.hpp:67:34:   required from ‘void boost::python::def_visitor<DerivedVisitor>::visit(classT&) const [with classT = boost::python::class_<Eigen::LLT<Eigen::Matrix<double, -1, -1>, 1>, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>; DerivedVisitor = eigenpy::LLTSolverVisitor<Eigen::Matrix<double, -1, -1> >]’
/usr/include/boost/python/class.hpp:221:9:   required from ‘boost::python::class_<T, X1, X2, X3>::self& boost::python::class_<T, X1, X2, X3>::def(const boost::python::def_visitor<Derived>&) [with Derived = eigenpy::LLTSolverVisitor<Eigen::Matrix<double, -1, -1> >; W = Eigen::LLT<Eigen::Matrix<double, -1, -1>, 1>; X1 = boost::python::detail::not_specified; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified; boost::python::class_<T, X1, X2, X3>::self = boost::python::class_<Eigen::LLT<Eigen::Matrix<double, -1, -1>, 1>, boost::python::detail::not_specified, boost::python::detail::not_specified, boost::python::detail::not_specified>]’
/home/cmastalli/devel/eigenpy/include/eigenpy/decompositions/LLT.hpp:83:7:   required from ‘static void eigenpy::LLTSolverVisitor<_MatrixType>::expose(const string&) [with _MatrixType = Eigen::Matrix<double, -1, -1>; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/cmastalli/devel/eigenpy/src/decompositions/decompositions.cpp:24:45:   required from here
/home/cmastalli/devel/eigenpy/include/eigenpy/decompositions/LLT.hpp:47:25: error: no matches converting function ‘rankUpdate’ to type ‘eigenpy::LLTSolverVisitor<Eigen::Matrix<double, -1, -1> >::Solver (class Eigen::LLT<Eigen::Matrix<double, -1, -1>, 1>::*)(const VectorType&, const RealScalar&) {aka class Eigen::LLT<Eigen::Matrix<double, -1, -1>, 1> (class Eigen::LLT<Eigen::Matrix<double, -1, -1>, 1>::*)(const class Eigen::Matrix<double, -1, 1>&, const double&)}’
       .def("rankUpdate",(Solver (Solver::*)(const VectorType &, const RealScalar &))&Solver::template rankUpdate<VectorType>,
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/eigen3/Eigen/Cholesky:32:0,
                 from /usr/local/include/eigen3/Eigen/Eigenvalues:13,
                 from /home/cmastalli/devel/eigenpy/include/eigenpy/decompositions/EigenSolver.hpp:10,
                 from /home/cmastalli/devel/eigenpy/src/decompositions/decompositions.cpp:10:
/usr/local/include/eigen3/Eigen/src/Cholesky/LLT.h:208:11: note: candidate is: template<class VectorType> Eigen::LLT<_MatrixType, _UpLo>& Eigen::LLT<MatrixType, UpLo>::rankUpdate(const VectorType&, const RealScalar&) [with VectorType = VectorType; _MatrixType = Eigen::Matrix<double, -1, -1>; int _UpLo = 1]
     LLT & rankUpdate(const VectorType& vec, const RealScalar& sigma = 1);
           ^~~~~~~~~~
```

**Comment by jcarpent** [comment]
It has been fixed by https://github.com/stack-of-tasks/eigenpy/pull/186. I suppose you have not checked that?

**Comment by cmastalli** [comment]
The code that I compiled uses the changes introduced in #186. However, I am still having this issue.
By inspecting that PR I noticed the follows:
```cpp
#if EIGEN_VERSION_AT_LEAST(3,3,90)
```

why are you defining v3.3.9? It should be 3.3.7, right?

**Comment by jcarpent** [comment]
No, everything works for 3.3.7. The master branch is in development mode for Eigen, so do not consider it as an official and released version.
3.3.90 means future release for 3.4.0.

**Comment by cmastalli** [comment]
Sorry, I thought I was using this PR. For some reason, I confused it.

I confirmed there is no issue.
